# Generated by Django 5.1.4 on 2025-01-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/Avatar.jpg', null=True, upload_to='uploads/'),
        ),
    ]
