# Generated by Django 5.1.4 on 2025-01-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_delete_movie_review_rename_name_movies_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_title',
            new_name='title',
        ),
    ]
