# Generated by Django 5.1.4 on 2025-01-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_movie_title_review_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='movie_title',
        ),
    ]
